#!/usr/bin/env bash
set -euo pipefail

# Upload clothing images from a folder and generate SQL to seed looks.
#
# Usage:
#   bash scripts/seed-looks-from-folder.sh \
#     --api-base "https://api.tvoiistyle.top" \
#     --folder "/ABS/PATH/looks" \
#     --store-id "11111111-1111-1111-1111-111111111111" \
#     --out "/tmp/seed_looks.sql" \
#     --deactivate-existing
#
# Notes:
# - Requires: curl, python3
# - Does NOT execute SQL; only generates file with INSERT statements.

API_BASE=""
FOLDER=""
STORE_ID="11111111-1111-1111-1111-111111111111"
OUT_FILE="./seed_looks.sql"
DEACTIVATE_EXISTING="false"
CLIENT_ID="seed-looks-$(date +%s)"
SCENE_TYPE="studio"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --api-base)
      API_BASE="${2:-}"
      shift 2
      ;;
    --folder)
      FOLDER="${2:-}"
      shift 2
      ;;
    --store-id)
      STORE_ID="${2:-}"
      shift 2
      ;;
    --out)
      OUT_FILE="${2:-}"
      shift 2
      ;;
    --scene-type)
      SCENE_TYPE="${2:-}"
      shift 2
      ;;
    --deactivate-existing)
      DEACTIVATE_EXISTING="true"
      shift
      ;;
    *)
      echo "Unknown arg: $1" >&2
      exit 1
      ;;
  esac
done

if [[ -z "$API_BASE" || -z "$FOLDER" ]]; then
  echo "Required args: --api-base and --folder" >&2
  exit 1
fi

if [[ ! -d "$FOLDER" ]]; then
  echo "Folder not found: $FOLDER" >&2
  exit 1
fi

tmp_json="$(mktemp)"
trap 'rm -f "$tmp_json"' EXIT

shopt -s nullglob
files=(
  "$FOLDER"/*.jpg
  "$FOLDER"/*.jpeg
  "$FOLDER"/*.png
  "$FOLDER"/*.webp
  "$FOLDER"/*.JPG
  "$FOLDER"/*.JPEG
  "$FOLDER"/*.PNG
  "$FOLDER"/*.WEBP
)
shopt -u nullglob

if [[ ${#files[@]} -eq 0 ]]; then
  echo "No images found in folder: $FOLDER" >&2
  exit 1
fi

echo "[]" > "$tmp_json"

for file in "${files[@]}"; do
  echo "Uploading: $file"
  resp="$(curl -sS -X POST "$API_BASE/api/media/upload" \
    -H "X-Client-Id: $CLIENT_ID" \
    -F "type=clothing" \
    -F "file=@$file")"

  asset_id="$(python3 - <<'PY' "$resp"
import json,sys
try:
    obj=json.loads(sys.argv[1])
    print((obj.get("assetId") or "").strip())
except Exception:
    print("")
PY
)"
  url="$(python3 - <<'PY' "$resp"
import json,sys
try:
    obj=json.loads(sys.argv[1])
    print((obj.get("url") or "").strip())
except Exception:
    print("")
PY
)"

  if [[ -z "$asset_id" ]]; then
    echo "Upload failed for: $file" >&2
    echo "Response: $resp" >&2
    exit 1
  fi

  title="$(basename "$file")"
  title="${title%.*}"

  python3 - <<'PY' "$tmp_json" "$asset_id" "$title" "$url"
import json,sys
path,asset_id,title,url = sys.argv[1],sys.argv[2],sys.argv[3],sys.argv[4]
with open(path,"r",encoding="utf-8") as f:
    data=json.load(f)
data.append({"asset_id": asset_id, "title": title, "url": url})
with open(path,"w",encoding="utf-8") as f:
    json.dump(data,f,ensure_ascii=False)
PY
done

python3 - <<'PY' "$tmp_json" "$OUT_FILE" "$STORE_ID" "$SCENE_TYPE" "$DEACTIVATE_EXISTING"
import json,sys

inp, outp, store_id, scene_type, deactivate = sys.argv[1:6]
rows = json.load(open(inp, "r", encoding="utf-8"))

def esc(s: str) -> str:
    return s.replace("'", "''")

with open(outp, "w", encoding="utf-8") as f:
    f.write("-- Generated by scripts/seed-looks-from-folder.sh\n")
    f.write("BEGIN;\n\n")
    if deactivate == "true":
        f.write("UPDATE looks SET is_active = FALSE, updated_at = NOW() WHERE is_active = TRUE;\n\n")

    f.write("INSERT INTO looks (store_id, title, description, main_asset_id, scene_type, is_active)\n")
    f.write("VALUES\n")
    values = []
    for r in rows:
        title = esc(r["title"])
        desc = esc(f"Seeded from file {r['title']}")
        asset = r["asset_id"]
        values.append(
            f"  ('{store_id}'::uuid, '{title}', '{desc}', '{asset}'::uuid, '{scene_type}', TRUE)"
        )
    f.write(",\n".join(values))
    f.write(";\n\nCOMMIT;\n")

print(f"SQL generated: {outp}")
print(f"Rows: {len(rows)}")
PY

echo
echo "Done."
echo "1) Review SQL: $OUT_FILE"
echo "2) Apply SQL:   psql -U <user> -d <db> -f \"$OUT_FILE\""

